<?php
/**
 * WebEngine CMS
 * https://webenginecms.org/
 * 
 * @version 1.2.0
 * @author Lautaro Angelico <http://lautaroangelico.com/>
 * @copyright (c) 2013-2019 Lautaro Angelico, All Rights Reserved
 * 
 * Licensed under the MIT license
 * http://opensource.org/licenses/MIT
 */

// WebEngine CMS Tables Prefix
define('WE_PREFIX', '');

// WebEngine CMS Tables
define('WEBENGINE_BANS', WE_PREFIX.'WEBENGINE_BANS');
define('WEBENGINE_BAN_LOG', WE_PREFIX.'WEBENGINE_BAN_LOG');
define('WEBENGINE_BLOCKED_IP', WE_PREFIX.'WEBENGINE_BLOCKED_IP');
define('WEBENGINE_CREDITS_CONFIG', WE_PREFIX.'WEBENGINE_CREDITS_CONFIG');
define('WEBENGINE_CREDITS_LOGS', WE_PREFIX.'WEBENGINE_CREDITS_LOGS');
define('WEBENGINE_CRON', WE_PREFIX.'WEBENGINE_CRON');
define('WEBENGINE_DOWNLOADS', WE_PREFIX.'WEBENGINE_DOWNLOADS');
define('WEBENGINE_FLA', WE_PREFIX.'WEBENGINE_FLA');
define('WEBENGINE_NEWS', WE_PREFIX.'WEBENGINE_NEWS');
define('WEBENGINE_PASSCHANGE_REQUEST', WE_PREFIX.'WEBENGINE_PASSCHANGE_REQUEST');
define('WEBENGINE_PAYPAL_TRANSACTIONS', WE_PREFIX.'WEBENGINE_PAYPAL_TRANSACTIONS');
define('WEBENGINE_PLUGINS', WE_PREFIX.'WEBENGINE_PLUGINS');
define('WEBENGINE_REGISTER_ACCOUNT', WE_PREFIX.'WEBENGINE_REGISTER_ACCOUNT');
define('WEBENGINE_VOTES', WE_PREFIX.'WEBENGINE_VOTES');
define('WEBENGINE_VOTE_LOGS', WE_PREFIX.'WEBENGINE_VOTE_LOGS');
define('WEBENGINE_VOTE_SITES', WE_PREFIX.'WEBENGINE_VOTE_SITES');
define('WEBENGINE_ACCOUNT_COUNTRY', WE_PREFIX.'WEBENGINE_ACCOUNT_COUNTRY');
define('WEBENGINE_NEWS_TRANSLATIONS', WE_PREFIX.'WEBENGINE_NEWS_TRANSLATIONS');